In [1]:
import pandas as pd
import numpy as np

In [2]:
crop=pd.read_csv(r"C:\Users\Legion\Downloads\archive (7)\Crop_Recommendation.csv")
crop.head()

Nitrogen  Phosphorus  Potassium  Temperature   Humidity  pH_Value  \
0        90          42         43    20.879744  82.002744  6.502985   
1        85          58         41    21.770462  80.319644  7.038096   
2        60          55         44    23.004459  82.320763  7.840207   
3        74          35         40    26.491096  80.158363  6.980401   
4        78          42         42    20.130175  81.604873  7.628473   

     Rainfall  Crop  
0  202.935536  Rice  
1  226.655537  Rice  
2  263.964248  Rice  
3  242.864034  Rice  
4  262.717340  Rice

# preprocessing

In [3]:
crop.shape

(2200, 8)

In [4]:
crop.isnull().sum()[crop.isnull().sum()>0]

Series([], dtype: int64)

In [5]:
crop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Nitrogen     2200 non-null   int64  
 1   Phosphorus   2200 non-null   int64  
 2   Potassium    2200 non-null   int64  
 3   Temperature  2200 non-null   float64
 4   Humidity     2200 non-null   float64
 5   pH_Value     2200 non-null   float64
 6   Rainfall     2200 non-null   float64
 7   Crop         2200 non-null   object 
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB


In [6]:
crop. Crop.unique()

array(['Rice', 'Maize', 'ChickPea', 'KidneyBeans', 'PigeonPeas',
       'MothBeans', 'MungBean', 'Blackgram', 'Lentil', 'Pomegranate',
       'Banana', 'Mango', 'Grapes', 'Watermelon', 'Muskmelon', 'Apple',
       'Orange', 'Papaya', 'Coconut', 'Cotton', 'Jute', 'Coffee'],
      dtype=object)

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
crop['Crop'] = le.fit_transform(crop['Crop'])


In [9]:
print(crop['Crop'])

0       20
1       20
2       20
3       20
4       20
        ..
2195     5
2196     5
2197     5
2198     5
2199     5
Name: Crop, Length: 2200, dtype: int32


In [11]:
x = crop.drop('Crop', axis=1)
y = crop['Crop']

# train _test splite

In [12]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=5)

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

# DecisionTree

In [21]:
from sklearn.tree import DecisionTreeClassifier
dec=DecisionTreeClassifier()

In [22]:
dec.fit(x_train, y_train)

DecisionTreeClassifier()

In [28]:
pred_train=dec.predict(x_train)
pred_test=dec.predict(x_test)

In [29]:
pred_test

array([ 7, 15,  4,  3, 21, 17, 17, 19, 18,  0,  4, 17, 19, 11,  2,  3,  6,
       15, 13, 19, 15,  3,  5, 19,  2,  8, 16, 21, 20, 16,  0, 13,  8,  8,
        1, 13, 20, 14,  9,  2, 12,  3, 11, 17,  1,  2,  4, 16, 16,  6,  5,
       13, 18, 16, 12, 16, 15, 18, 14, 13,  6,  2,  3,  6, 14, 14,  3, 17,
        4,  1,  8, 11, 19, 21,  1,  9, 17,  0,  7,  3,  3,  1,  0, 11,  0,
       15,  1,  3, 20, 17, 18, 16, 12,  5, 15, 19, 18, 21,  5,  7, 20,  4,
       11, 11, 13,  2, 16, 18, 18, 11, 18, 12, 12, 19, 10,  2, 18, 15,  0,
       10,  4, 15, 10, 11, 12,  5,  6,  2,  5, 18,  2, 11,  4,  5, 16,  4,
       14,  2, 11,  0, 16, 11,  0, 17, 15, 19,  2, 19, 13, 14,  7,  1, 10,
       20, 18,  5, 14, 13, 21,  8, 10,  0, 20, 14, 14, 16,  8,  9, 18, 18,
       15,  7, 11, 12,  9,  3, 21, 19, 10, 10, 21,  7, 17,  5,  0,  4, 21,
       17,  6, 20,  5,  3,  0, 19, 17,  7, 11, 21,  4,  1, 17, 11,  2,  6,
       20, 13,  5,  4, 11, 14, 13, 10,  3,  6, 15, 21, 11, 11,  2, 15, 17,
        0, 16,  5,  0,  6

In [40]:
pred_train

array([14,  8,  7, ...,  5, 15, 17])

In [36]:
from sklearn.metrics import precision_score

In [27]:
from sklearn.metrics import confusion_matrix,accuracy_score,f1_score,recall_score,precision_score

In [30]:
mat_test=confusion_matrix( y_test,pred_test)
mat_test

array([[24,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0, 15,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0, 22,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 19,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 20,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 25,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 17,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 13,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  2,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 16,  0,  0,

In [31]:
accuracy_score( y_test,pred_test)

0.9840909090909091

In [41]:
accuracy_score( y_train,pred_train)

1.0

In [44]:
precision = precision_score(y_test, pred_test, average='macro')
print(f'Precision Score: {precision}')

Precision Score: 0.9814427028447025


In [81]:
f1_score(y_test,pred_test,average='macro')

0.9815344336674259

In [45]:
recall_score(y_test, pred_test,average='macro')

0.98236149372513

# Decision Tree with entropy

In [46]:
from sklearn.tree import DecisionTreeClassifier
dec=DecisionTreeClassifier(criterion="entropy")

In [48]:
dec.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [49]:
dec_pred_ent_test=dec.predict(x_test)

In [50]:
confusion_matrix(y_test,dec_pred_ent_test)

array([[22,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  2,  0,  0,  0,  0],
       [ 0, 15,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0, 21,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 19,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 20,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 25,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 17,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 14,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 16,  0,  0,

In [51]:
accuracy_score(y_test,dec_pred_ent_test)

0.975

# Random Forest

In [52]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()

In [53]:
rfc.fit(x_train, y_train)

RandomForestClassifier()

In [54]:
rfc_pred_train=rfc.predict(x_train)
rfc_pred_test=rfc.predict(x_test)

In [55]:
confusion_matrix(y_test,rfc_pred_test)

array([[24,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0, 15,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0, 22,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 19,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 20,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 25,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 17,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 15,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 16,  0,  0,

In [70]:
accuracy_score(y_test,rfc_pred_test)

0.9977272727272727

In [77]:
precision = precision_score(y_test, rfc_pred_test, average='macro')
print(f'Precision Score: {precision}')

Precision Score: 0.9971590909090909


In [78]:
f1_score(y_test,rfc_pred_test,average='macro')

0.9969663262210537

In [80]:
recall_score(y_test,rfc_pred_test,average='macro')

0.996969696969697

# Logistic

In [56]:
from sklearn.linear_model import LogisticRegression
logreg= LogisticRegression()

In [57]:
logreg.fit(x_train,y_train)

LogisticRegression()

In [58]:
logreg_pred_test=logreg.predict(x_test)

In [59]:
confusion_matrix(y_test, logreg_pred_test)

array([[24,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0, 15,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0, 20,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 19,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 20,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 25,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 12,  0,  0,  0,  0,  1,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 17,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 14,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 15,  0,  0,

In [60]:
accuracy_score(y_test, logreg_pred_test)

0.9659090909090909

In [82]:
precision = precision_score(y_test, logreg_pred_test, average='macro')
print(f'Precision Score: {precision}')

Precision Score: 0.9640534089337917


In [83]:
f1_score(y_test, logreg_pred_test,average='macro')

0.9643481812657838

In [84]:
recall_score(y_test, logreg_pred_test,average='macro')

0.9653701106023239

# hyper parameter tunnig using rfc

In [62]:
from sklearn.model_selection import GridSearchCV

search_dict = {
    'n_estimators': [50, 100, 150], 
    'criterion': ['gini', 'entropy'], 
    'max_depth': [4, 8, 12, 16, 20], 
    'min_samples_split': [50, 60, 70, 80, 90, 100]
}

rfc = RandomForestClassifier()
grid_search = GridSearchCV(rfc, param_grid=search_dict)
grid_search.fit(x_train,y_train)
grid_search.best_params_

{'criterion': 'entropy',
 'max_depth': 16,
 'min_samples_split': 50,
 'n_estimators': 100}

In [63]:
from sklearn.ensemble import RandomForestClassifier
rfc =RandomForestClassifier(criterion = 'gini',
 max_depth = 4,
 min_samples_split= 60,
 n_estimators= 150)

In [64]:
rfc.fit(x_train,y_train)

RandomForestClassifier(max_depth=4, min_samples_split=60, n_estimators=150)

In [65]:
pred_test_grid=rfc.predict(x_test)

In [66]:
confusion_matrix(y_test,pred_test_grid)

array([[24,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0, 15,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0, 22,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 19,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 20,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 25,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 17,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 15,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 16,  0,  0,

In [67]:
accuracy_score(y_test,pred_test_grid)

0.95

# conclusion

In [ ]:
model works best on  RandomForest